language: node_js
node_js:
- 0.12
before_install: npm install -g grunt-cli
install: npm install
before_script: 
  - grunt
  - ls dist/lib1self-client*.js
  - ls dist/lib1self-client*.js | grep -P "v\d+.\d+.\d+.js"
before_deploy:
  - export ENV_TEST=$(echo "this is a test")
  - echo $ENV_TEST
  - ls dist
  - ls dist/lib1self-client*.js | grep -P "v\d+.\d+.\d+.js"
  - export DEBUG_FILE=$(ls dist/lib1self-client*.js | grep -P "v\d+.\d+.\d+.js")
  - echo "deploying debug file $DEBUG_FILE to github releases"
  - export REL_FILE=$(ls dist/lib1self-client*.js | grep -P "v\d+.\d+.\d+.min.js")
  - echo "deploying release file $REL_FILE to github releases"
deploy:
  provider: releases
  api_key:
    secure: sM7+YbZfH/mB48dGjF4X1hQmTFqlLGpX3/L7g4PgBBSr+qjJC+Wkdz2fSmICpWEaMWJMj1tpAfUcbGBrNxONl9m2EE7cqhw3yCAxXDpUVV2y/SFM7WVnsCTn0XPzCplR8Nze3gVcwK/mhfTOTfR2pPJFgCU97FYxQHC9iDxcGDA=
  file_glob: true
  file: 
  - ${DEBUG_FILE}
  - ${REL_FILE}
  on:
    tags: true
    repo: 1self/lib1self-client
    all_branches: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2a5a368d80efd6c35282
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
