language: node_js
node_js:
- 0.8
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt
deploy:
  provider: releases
  api_key:
    secure: sM7+YbZfH/mB48dGjF4X1hQmTFqlLGpX3/L7g4PgBBSr+qjJC+Wkdz2fSmICpWEaMWJMj1tpAfUcbGBrNxONl9m2EE7cqhw3yCAxXDpUVV2y/SFM7WVnsCTn0XPzCplR8Nze3gVcwK/mhfTOTfR2pPJFgCU97FYxQHC9iDxcGDA=
  file:
  - dist/lib1self-client.v0.1.3.js
  - dist/lib1self-client.v0.1.3.min.js
  on:
    repo: 1self/lib1self-client
  all_branches: true
