language: node_js
node_js:
- 0.12
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt
before_deploy:
  - ls dist
  - export DEBUG_FILE=$(ls dist/lib1self-client*.js | egrep "v\d+.\d+.\d+.js")
  - echo debug file is ${DEBUG_FILE}
  - export REL_FILE=$(ls dist/lib1self-client*.js | egrep "v\d+.\d+.\d+.min.js")
  - echo release file is ${REL_FILE}
deploy:
  provider: releases
  api_key:
    secure: sM7+YbZfH/mB48dGjF4X1hQmTFqlLGpX3/L7g4PgBBSr+qjJC+Wkdz2fSmICpWEaMWJMj1tpAfUcbGBrNxONl9m2EE7cqhw3yCAxXDpUVV2y/SFM7WVnsCTn0XPzCplR8Nze3gVcwK/mhfTOTfR2pPJFgCU97FYxQHC9iDxcGDA=
  file:
  - ${DEBUG_FILE}
  - ${REL_FILE}
  on:
    tags: true
    repo: 1self/lib1self-client
    all_branches: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2a5a368d80efd6c35282
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
